spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1022zhang
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jpa:
    database : MYSQL
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.116.149
    port: 6379
server:
  servlet:
    context-path: /sell
wechat:
  myAppId: wx085c556cb1d22b1f   #微信公众平台测试账号
  myAppSecret: 306416745e957da269b33ac134df28fd   #微信公众平台账号秘钥
  openAppId: wx277996c4d2772104  #微信开放平台账号
  openAppSecret: b5e4052a545c997a6f98fe0579860bd1 #微信开放平台账号秘钥
  mchId: 4011056368   #商户号
  mchKey: OjE471C8EaL6aBM15E851qL9J60890S1  #微信支付秘钥
  keyPath: /var/weixin_cert/h5.p12  #微信支付授权地址
  notifyUrl: http://t238997p11.qicp.vip/sell/pay/notify
  #消息模板推送
  templateId:
      orderStatus: Iyqg2KLTaMJKKveaciV6BvrPYnVKFi_8Tp5mZT1nK5I
project:
  wechatMpAuthorize: http://t238997p11.qicp.vip  #微信公众平台授权访问基础地址（授权域名）
  wechatOpenAuthorize: http://testdev.tunnel.qydev.com  #微信开放平台授权访问基础地址（授权域名）
  sell: http://t238997p11.qicp.vip #项目地址
ftp:
  address: 192.168.116.149
  port: 21
  username: ftpuser
  password: ftpuser
  bastPath: /home/ftpuser/www/images
  imageBaseUrl: http://192.168.116.149/images

